### ISSUE TITLE
skyfield.api circular import crash

### ISSUE THREAD

**Issue by jrs65** [skyfielders/python-skyfield#97]
In commit d8d41345 it seems that a circular import was introduced that causes a crash when`skyfield.api` is imported.

```python
>>> from skyfield import api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "skyfield/api.py", line 18, in <module>
    from .named_stars import NamedStar
  File "skyfield/named_stars.py", line 5, in <module>
    from .data import hipparcos
  File "skyfield/data/hipparcos.py", line 2, in <module>
    from skyfield import api
ImportError: cannot import name api
```

A simple fix is to move the import into the `skyfield.data.hipparcos.load` routine that needs it.

I'll try and submit a PR with this later today.

**Comment by brandon-rhodes** [comment]
Oddly enough, I can't reproduce this — what Python version are you using? Could that be the difference between my setup and yours?

**Comment by jrs65** [comment]
Oh, sorry, forgot to say. This is in Python 2.7.10, on OS X 10.11.6. I can imagine things have changed significantly in Python 3, if that's what you are mostly using.

**Comment by jrs65** [comment]
Just to confirm, it seems to work fine on Python 3.5. I only have the issue on 2.7.

**Comment by brandon-rhodes** [comment]
Thanks for contributing 176fdef7df325defc6cfa789e65261b71b84eafb which fixed this!
