### ISSUE TITLE
How to correctly build linear combinations of time objects (e.g. weighted averages)?

### ISSUE THREAD

**Issue by davidmikolas** [skyfielders/python-skyfield#150]
The simplest possible example would be to propagate a satellite forward *to the midpoint in time* between a selected TLE's epoch and the epoch of the spacecraft's next TLE.

The following script appears on the surface to work, but `Time.__doc__` says:

>You will typically not instantiate this class yourself, but will
>rely on a Skyfield ``Timescale`` object to build dates for you:

My results for the difference between propagating one TLE forward and the following day's TLE backward to the midpoint of `Δ position = [-0.1103371   0.0229925  -0.07156896]` of much less than a kilometer make sense for a close pair of TLEs for the closely-watched, newly-launched satellite IRIDIUM 135.

**Question:** But is this in fact an absolutely correct way to build linear combinations of time objects derived from TLE epochs?  (`Time(ts, 0.5*(JD_1 + JD_2))`)

    text = """1 43070U 17083A   17363.51227664 -.00000051  00000-0 -95710-5 0  9991
    2 43070  86.6915 174.0210 0012197 236.9667 123.0385 14.83239028   951
    1 43070U 17083A   17364.52424882 -.00000023  00000-0 -62098-5 0  9996
    2 43070  86.6916 173.6010 0012275 232.7276 127.2829 14.83238956  1108"""
    lines = text.splitlines()                    

    import numpy as np

    from skyfield.api import Loader, EarthSatellite
    from skyfield.timelib import Time

    load = Loader('~/Documents/SkyData')
    ts   = load.timescale()

    sat_tle_1 = EarthSatellite(lines[0], lines[1])
    sat_tle_2 = EarthSatellite(lines[2], lines[3])

    JD_1      = sat_tle_1.epoch.tt
    JD_2      = sat_tle_2.epoch.tt

    timeobj_midpoint = Time(ts, 0.5*(JD_1 + JD_2))              # is this correct?

    sat_tle_1_midpos = sat_tle_1.at(timeobj_midpoint).position.km
    sat_tle_2_midpos = sat_tle_2.at(timeobj_midpoint).position.km

    print sat_tle_2_midpos - sat_tle_1_midpos

**Comment by brandon-rhodes** [comment]
Since those JD values are presumably in UTC, you might instead do:
```
timeobj_midpoint = ts.utc(0.5*(JD_1 + JD_2))
```
Do you get a good result from that expression? The difference should be a few dozen seconds.

**Comment by davidmikolas** [comment]
I tried that. I'm using version 1.0 and

    Time(ts, 0.5*(JD_1 + JD_2)).tt
    ts.utc(  0.5*(JD_1 + JD_2)).tt

Returns respectively

    2458117.51906
    899529862.501

where the utc is using `2458117.51906` as a value for year, ergo the factor of ~366 difference.

Am I missing something? It does not appear to work.

**Comment by brandon-rhodes** [comment]
The result in your initial post should be correct, yes, but uses the undocumented instantiator for `Time`.

My own answer was incorrect, I suspect, because I provided the JD as a year, as you note — I forgot to use the keyword `jd=` to warn Skyfield that I was providing a JD:

```
timeobj_midpoint = ts.utc(jd=0.5*(JD_1 + JD_2))
```

**Comment by davidmikolas** [comment]
I'm guessing that will start working in version 1.1? 

    >>> skyfield.__version__
    '1.0'
    >>> ts.utc(jd=2458119.5).tt

    Traceback (most recent call last):
      File "<pyshell#53>", line 1, in <module>
        ts.utc(jd=2458119.5).tt
    TypeError: utc() got an unexpected keyword argument 'jd'

**Comment by brandon-rhodes** [comment]
You can't specify a UTC time with a JD float, because it would create an ambiguity each time there's a leap second — thus my example used Terrestrial Time (TT), because it never suffers from leap seconds.

**Comment by davidmikolas** [comment]
That certainly makes more sense. I had copied from the initial e-mail that GitHub generates when one first posts, didn't notice that you had (probably immediately) edited it.

>![shot](https://user-images.githubusercontent.com/17236804/34978505-665d6b72-fad9-11e7-8f6a-c9f768c5a4d4.png)

So both B and C return the same position as A.

    A  = sat_tle_1.at(sat_tle_1.epoch).position.km
    JD = sat_tle_1.epoch.tt
    B  = sat_tle_1.at(Time(ts, JD)).position.km
    C  = sat_tle_1.at(ts.tt(jd=JD)).position.km

but using "B" is bad because it will create an ambiguity near any leap second.

"C" is the correct way to calculate positions using a JD float? 

Sorry for the back-and-forth, time is hard for some of us.

**Comment by brandon-rhodes** [comment]
"C" is, yes, certainly the fastest and best supported way to create a time from a JD float. You could also use any of the other timescales besides TT, but it's the base timescale that's used underneath the hood.

**Comment by davidmikolas** [comment]
OK thanks for all of your help!
